### ISSUE TITLE
XOPPY BM bug

### ISSUE THREAD

**Issue by maltissimo** [srio/Orange-XOPPY#112]
Hello, 

there's a bug in XOPPY's BM, I think it's just a typo in the code. See the attached image. 

<img width="1315" alt="image" src="https://github.com/oasys-kit/XOPPY/assets/41440861/5582805c-83b4-48ea-be15-7fb5565f1146">

Cheers

Matteo

**Comment by srio** [comment]
Yes... problem accessing physical constants. Please update xoppy and it should be solved.
Thanks a lot for pointing out this problem!

**Comment by maltissimo** [comment]
Thank you!
