### ISSUE TITLE
WS widget give empty results with default values

### ISSUE THREAD

**Issue by lucarebuffi** [srio/Orange-XOPPY#19]
Check the WS widget: it gives an empty spec file after calling the calculation routine.

**Comment by srio** [comment]
Not for me. Check that ws.inp is written. FOr default inputs:
`Wiggler A at APS
7.000000     100.000000
8.500000  28  0.000000  8.740000
1000.000000  100000.000000   2000.000000
30.000000  0.000000  0.000000  2.000000  2.000000  10.000000  10.000000
4
`
and after running ws it should create ws.out, and ws.spec.

However, you see in my last applications I removed the creation of the spec file and I just send an Oasys Exchange object

**Comment by lucarebuffi** [comment]
I have this

 ****************** Start WS v. 1.61 at 2016-08-23 19:20:29 ******************

At line 316 of file ws.f (unit = 1, file = 'ws.inp')
Fortran runtime error: Bad integer for item 3 in list input

**Comment by lucarebuffi** [comment]
Here are the files produce by the program

![screen shot 2016-08-23 at 19 26 30](https://cloud.githubusercontent.com/assets/6713598/17902410/96485dba-6967-11e6-8cd0-ef5cd2fe261f.png)
