### ISSUE TITLE
Undulators: SRW library (srwlib) not present in Linux

### ISSUE THREAD

**Issue by lucarebuffi** [srio/Orange-XOPPY#34]

**Comment by lucarebuffi** [comment]
![screen shot 2016-09-22 at 20 21 11](https://cloud.githubusercontent.com/assets/6713598/18760619/215e68e8-8102-11e6-92ca-685105530d5a.png)

**Comment by srio** [comment]
I would not try to distribute SRW now. Unless it is easy to pack the libraries in xoppy. You decide. In the future we will see.  I wrote the srundplug to compare also with SRW. I think it is not a major problem to see that error message. If you want we can hide this call, but can be useful if you have SRW installed (like me).

**Comment by lucarebuffi** [comment]
I will just send a better message
