### ISSUE TITLE
POWER should accept an input signal from Source

### ISSUE THREAD

**Issue by srio** [srio/Orange-XOPPY#37]
in such a case, the Source (first item) should deactivate

**Comment by lucarebuffi** [comment]
Please clarify

**Comment by lucarebuffi** [comment]
1 - Which sources are good candidate?
2 - Which information should be carried
3 - Which format is accepted?

**Comment by srio** [comment]
1 - Every source producing a spectrum: undulator_spectrum, BM, WS, WIGGLER, XTUBES, XTUBE_W BlackBody

2 - The energy spectrum.
     If available (Photon_Energy, Spectral_Power) 
     If not, whatever they calculate (XTUBE, XTUBE_S)

3 - I think the exchange object you use to feed the shadow geometrical source.
