### ISSUE TITLE
XCOM not working!!!!!

### ISSUE THREAD

**Issue by lucarebuffi** [srio/Orange-XOPPY#48]
There is a problem with file names length:

here the output:

  Save additional energies in file? (Y/N): 
At line 86 of file xcom.f (unit = 7, file = '/Users/admin/Documents/workspace/OASYS-Develop/1.0.beta/XOPPY/orangecontrib/xoppy/util/datMDATX3.005')

the file name is limited to 100 characters.

**Comment by srio** [comment]
I recompiled. Only in Mac. try this binary: 
https://github.com/lucarebuffi/xoppy_external_codes/blob/master/bin/darwin/xcom

I cannot check, my installation has a shorter path
