### ISSUE TITLE
Virtual machine

### ISSUE THREAD

**Issue by Angelrf86** [srio/Orange-XOPPY#58]
Hi all,

I am trying to download the virtual machine to install the Oasys Orange suite in a windows machine and the link in https://www.elettra.trieste.it/oasys.html it seems not to work properly. Could you help me with it? 

thanks

**Comment by lucarebuffi** [comment]
I'm sorry, but I verified and it works correctly. Please check your connection and/or your network restrictions.

**Comment by Angelrf86** [comment]
Hi Luca,

It is working good with Mozilla firefox, but gives problems with explorer (is this extrange or just another user-friendly feature of windows) . Thank you for your fast reply.

How could I make the .vdi file to have more than 12 GB?

**Comment by lucarebuffi** [comment]
I am pretty sure that you can't. By the way you can create a link with the real machine hard disk.

Follow this:

http://www.howtogeek.com/187703/how-to-access-folders-on-your-host-machine-from-an-ubuntu-virtual-machine-in-virtualbox/
