### ISSUE TITLE
XOPPY not working in MAC

### ISSUE THREAD

**Issue by lucarebuffi** [srio/Orange-XOPPY#6]
srundplug: undefined home_bin. It has been set to  /users/srio/Oasys/Orange-XOPPY/orangecontrib/xoppy/bin.linux/
srundplug: File not found: /users/srio/Oasys/Orange-XOPPY/orangecontrib/xoppy/bin.linux/urgent
srundplug: File not found: /users/srio/Oasys/Orange-XOPPY/orangecontrib/xoppy/bin.linux/us

What is the best way to properly set it?

**Comment by srio** [comment]
In mac home_bin must point to .../Oasys/Orange-XOPPY/orangecontrib/xoppy/bin.darwin/

This is done in __init__.py in orangecontrib/xoppy

But not always working, I do not know why...

**Comment by lucarebuffi** [comment]
I fixed into:

xoppy_home = resources.package_dirname("orangecontrib.xoppy")

def xoppy_home():
    return xoppy_home

def home_bin():
    return os.path.join(xoppy_home, 'bin.' + sys.platform + '/')

def home_doc():
    return os.path.join(xoppy_home, 'doc_txt/')

def home_data():
    return os.path.join(xoppy_home, 'data/')

def home_testrun():
    return os.path.join(xoppy_home, 'testrun/')

then into the srundulplug.py:

# directory  where to find urgent and us binaries
try:
    home_bin = xoppy.home_bin()
except NameError:
    if platform.system() == 'Linux':
        home_bin='/scisoft/xop2.4/bin.linux/'
        print("srundplug: undefined home_bin. It has been set to ", home_bin)
    elif platform.system() == 'Darwin':
        home_bin = "/scisoft/xop2.4/bin.darwin/"
        print("srundplug: undefined home_bin. It has been set to ", home_bin)
    else:
        raise FileNotFoundError("srundplug: undefined home_bin")
#check

if os.path.isfile(home_bin + 'us') == False:
    print("srundplug: File not found: "+home_bin+'us')
if os.path.isfile(home_bin + 'urgent') == False:
    raise FileNotFoundError("srundplug: File not found: "+ home_bin + 'urgent')
