### ISSUE TITLE
Undulator Radiation cannot plot a single energy

### ISSUE THREAD

**Issue by lucarebuffi** [srio/Orange-XOPPY#63]
![screen shot 2017-07-24 at 15 28 46](https://user-images.githubusercontent.com/6713598/28525550-ec2a7fea-7084-11e7-93a5-dcb459523c70.png)

**Comment by srio** [comment]
OK, 2 is the minimum, now there is a new message:

![image](https://user-images.githubusercontent.com/502315/28779935-3bd7b1b8-7605-11e7-8037-af8b618f04c7.png)

**Comment by lucarebuffi** [comment]
I added a small correction, too.
